name: Run Tests

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test


  deploy-local:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: hieubeo2369/api:${{ github.ref_name }}


    - name: Checkout helm config repo
      uses: actions/checkout@v2
      with:
        repository: HieuNT-2306/cloud_final_helm_api
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: cloud_final_helm_api

    - name: Update values.yaml
      run: |
        sed -i 's/tag: .*/tag: ${{ github.ref_name }}/' cloud_final_helm_api/api/values.yaml
 
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        cd cloud_final_helm_api
        git config --global user.name '${{ secrets.USER_NAME }}'
        git config --global user.email '${{ secrets.USER_EMAIL }}'
        git add -A
        git commit -m "Update image tag to ${{ github.ref_name }}"
        git push origin master
